apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: harold-ingress
        namespace: harold
      spec:
        rules:
          - host: harold.example.com  # <-- change this to your hostname
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: harold-app
                      port:
                        number: 80
