apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: harold-worker-hpa
  namespace: harold
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: harold-worker
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
